import type { Metadata } from "next";
import "./globals.css";
import { helveticaNow } from "../styles/fonts";
import { ThemeProvider } from "@mui/material";
import muiTheme from "../styles/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Providers } from "../components/Providers";
import ClientToaster from "@/components/ClientToaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${helveticaNow.variable}`}>
      <body>
        <Providers>
          <AppRouterCacheProvider>
            <ThemeProvider theme={muiTheme}>{children}</ThemeProvider>
          </AppRouterCacheProvider>
        </Providers>
        <ClientToaster /> {/* ✅ Only runs on the client */}
      </body>
    </html>
  );
}
